[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
ascii_table = "4.0.3"

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
